In [181]:
! pip install pandas

Requirement already satisfied: pandas in c:\Users\hp\OneDrive\Desktop\training\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\hp\OneDrive\Desktop\training\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\hp\OneDrive\Desktop\training\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\hp\OneDrive\Desktop\training\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\hp\OneDrive\Desktop\training\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [182]:
import os
import numpy as np
import pandas as pd

In [183]:
data = pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\Used_Bikes.csv")

In [184]:
data

,Unnamed: 0,city,owner,brand,kms_driven,age,power
0,0,Ahmedabad,First Owner,TVS,17654.0,3.0,110.0
1,1,Delhi,First Owner,Royal Enfield,11000.0,4.0,350.0
2,2,Delhi,First Owner,Triumph,110.0,8.0,675.0
3,3,Bangalore,First Owner,TVS,16329.0,4.0,180.0
4,4,Bangalore,First Owner,Yamaha,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
7225,9362,Delhi,First Owner,Hero,48587.0,8.0,150.0
7226,9369,Bangalore,First Owner,Bajaj,60000.0,9.0,220.0
7227,9370,Jodhpur,First Owner,Harley-Davidson,3430.0,4.0,750.0
7228,9371,Hyderabad,First Owner,Bajaj,21300.0,4.0,400.0
7229,9372,Hyderabad,First Owner,Bajaj,7127.0,5.0,220.0

In [185]:
data.describe

<bound method NDFrame.describe of       Unnamed: 0       city        owner            brand  kms_driven  age  \
0              0  Ahmedabad  First Owner              TVS     17654.0  3.0
1              1      Delhi  First Owner    Royal Enfield     11000.0  4.0
2              2      Delhi  First Owner          Triumph       110.0  8.0
3              3  Bangalore  First Owner              TVS     16329.0  4.0
4              4  Bangalore  First Owner           Yamaha     10000.0  3.0
...          ...        ...          ...              ...         ...  ...
7225        9362      Delhi  First Owner             Hero     48587.0  8.0
7226        9369  Bangalore  First Owner            Bajaj     60000.0  9.0
7227        9370    Jodhpur  First Owner  Harley-Davidson      3430.0  4.0
7228        9371  Hyderabad  First Owner            Bajaj     21300.0  4.0
7229        9372  Hyderabad  First Owner            Bajaj      7127.0  5.0

      power
0     110.0
1     350.0
2     675.0
3     180.0
4     150.0
...     ...
7225  150.0
7226  220.0
7227  750.0
7228  400.0
7229  220.0

[7230 rows x 7 columns]>

In [186]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7230 entries, 0 to 7229
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7230 non-null   int64
 1   city        7230 non-null   str
 2   owner       7230 non-null   str
 3   brand       7230 non-null   str
 4   kms_driven  7230 non-null   float64
 5   age         7230 non-null   float64
 6   power       7230 non-null   float64
dtypes: float64(3), int64(1), str(3)
memory usage: 395.5 KB

In [187]:
data.head()

   Unnamed: 0       city        owner          brand  kms_driven  age  power
0           0  Ahmedabad  First Owner            TVS     17654.0  3.0  110.0
1           1      Delhi  First Owner  Royal Enfield     11000.0  4.0  350.0
2           2      Delhi  First Owner        Triumph       110.0  8.0  675.0
3           3  Bangalore  First Owner            TVS     16329.0  4.0  180.0
4           4  Bangalore  First Owner         Yamaha     10000.0  3.0  150.0

In [188]:
data.head(10)

   Unnamed: 0       city         owner          brand  kms_driven  age  power
0           0  Ahmedabad   First Owner            TVS     17654.0  3.0  110.0
1           1      Delhi   First Owner  Royal Enfield     11000.0  4.0  350.0
2           2      Delhi   First Owner        Triumph       110.0  8.0  675.0
3           3  Bangalore   First Owner            TVS     16329.0  4.0  180.0
4           4  Bangalore   First Owner         Yamaha     10000.0  3.0  150.0
5           5      Delhi   First Owner         Yamaha     25000.0  6.0  150.0
6           6      Delhi   First Owner          Honda      8200.0  3.0  160.0
7           7      Delhi   First Owner           Hero     12645.0  3.0  100.0
8           8  Bangalore   First Owner  Royal Enfield      9190.0  3.0  350.0
9           9      Delhi  Second Owner  Royal Enfield     19000.0  7.0  500.0

In [189]:
data.tail()

,Unnamed: 0,city,owner,brand,kms_driven,age,power
7225,9362,Delhi,First Owner,Hero,48587.0,8.0,150.0
7226,9369,Bangalore,First Owner,Bajaj,60000.0,9.0,220.0
7227,9370,Jodhpur,First Owner,Harley-Davidson,3430.0,4.0,750.0
7228,9371,Hyderabad,First Owner,Bajaj,21300.0,4.0,400.0
7229,9372,Hyderabad,First Owner,Bajaj,7127.0,5.0,220.0

In [190]:
data.age

0       3.0
1       4.0
2       8.0
3       4.0
4       3.0
       ...
7225    8.0
7226    9.0
7227    4.0
7228    4.0
7229    5.0
Name: age, Length: 7230, dtype: float64

In [191]:
data.brand

0                   TVS
1         Royal Enfield
2               Triumph
3                   TVS
4                Yamaha
             ...
7225               Hero
7226              Bajaj
7227    Harley-Davidson
7228              Bajaj
7229              Bajaj
Name: brand, Length: 7230, dtype: str

In [192]:
data[['brand']]

                brand
0                 TVS
1       Royal Enfield
2             Triumph
3                 TVS
4              Yamaha
...               ...
7225             Hero
7226            Bajaj
7227  Harley-Davidson
7228            Bajaj
7229            Bajaj

[7230 rows x 1 columns]

In [193]:
data[['owner']]

            owner
0     First Owner
1     First Owner
2     First Owner
3     First Owner
4     First Owner
...           ...
7225  First Owner
7226  First Owner
7227  First Owner
7228  First Owner
7229  First Owner

[7230 rows x 1 columns]

In [194]:
data['brand'].unique

<bound method Series.unique of 0                   TVS
1         Royal Enfield
2               Triumph
3                   TVS
4                Yamaha
             ...
7225               Hero
7226              Bajaj
7227    Harley-Davidson
7228              Bajaj
7229              Bajaj
Name: brand, Length: 7230, dtype: str>

In [195]:
data['bike_name'].unique

KeyError: 'bike_name'

In [ ]:
data['brand'].nunique()

23

In [ ]:
data['bike_name'].nunique()

471

In [ ]:
data['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [ ]:
data['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(25324)

In [ ]:
data.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
data

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
data.dropna(inplace=True)

In [ ]:
data

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
data.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [ ]:
data.drop('city',axis = 1)

,bike_name,price,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
data.drop(['bike_name', 'price'], axis=1, inplace=True)

In [ ]:
data

           city  kms_driven        owner  age  power            brand
0     Ahmedabad     17654.0  First Owner  3.0  110.0              TVS
1         Delhi     11000.0  First Owner  4.0  350.0    Royal Enfield
2         Delhi       110.0  First Owner  8.0  675.0          Triumph
3     Bangalore     16329.0  First Owner  4.0  180.0              TVS
4     Bangalore     10000.0  First Owner  3.0  150.0           Yamaha
...         ...         ...          ...  ...    ...              ...
9362      Delhi     48587.0  First Owner  8.0  150.0             Hero
9369  Bangalore     60000.0  First Owner  9.0  220.0            Bajaj
9370    Jodhpur      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  Hyderabad     21300.0  First Owner  4.0  400.0            Bajaj
9372  Hyderabad      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [ ]:
char = data.select_dtypes(include='object')
num = data.select_dtypes(exclude='object')

C:\Users\hp\AppData\Local\Temp\ipykernel_16096\3520505256.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char = data.select_dtypes(include='object')

In [ ]:
char = data.select_dtypes(include='O')
num = data.select_dtypes(exclude='O')

C:\Users\hp\AppData\Local\Temp\ipykernel_16096\601300982.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char = data.select_dtypes(include='O')

# Encoding

In [ ]:
char['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
owner_dict = {'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}

In [ ]:
char['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

brand_dict = { 'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':20,              'MV':21,           'Ideal':22}

char['brand']=char['brand'].map(brand_dict)
char

In [ ]:
total_data=pd.concat([char,num], axis = 1)

In [ ]:
total_data

           city        owner            brand  kms_driven  age  power
0     Ahmedabad  First Owner              TVS     17654.0  3.0  110.0
1         Delhi  First Owner    Royal Enfield     11000.0  4.0  350.0
2         Delhi  First Owner          Triumph       110.0  8.0  675.0
3     Bangalore  First Owner              TVS     16329.0  4.0  180.0
4     Bangalore  First Owner           Yamaha     10000.0  3.0  150.0
...         ...          ...              ...         ...  ...    ...
9362      Delhi  First Owner             Hero     48587.0  8.0  150.0
9369  Bangalore  First Owner            Bajaj     60000.0  9.0  220.0
9370    Jodhpur  First Owner  Harley-Davidson      3430.0  4.0  750.0
9371  Hyderabad  First Owner            Bajaj     21300.0  4.0  400.0
9372  Hyderabad  First Owner            Bajaj      7127.0  5.0  220.0

[7324 rows x 6 columns]

In [ ]:
total_data.isnull().sum()

city          0
owner         0
brand         0
kms_driven    0
age           0
power         0
dtype: int64

In [ ]:
total_data.drop_duplicates(inplace=True)

In [ ]:
total_data.to_csv(r"C:\Users\hp\OneDrive\Desktop\Used_Bikes.csv")

In [197]:
import numpy as np
import pandas as pd
import os
data = pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\Used_Bikes.csv")

In [198]:
data

,Unnamed: 0,city,owner,brand,kms_driven,age,power
0,0,Ahmedabad,First Owner,TVS,17654.0,3.0,110.0
1,1,Delhi,First Owner,Royal Enfield,11000.0,4.0,350.0
2,2,Delhi,First Owner,Triumph,110.0,8.0,675.0
3,3,Bangalore,First Owner,TVS,16329.0,4.0,180.0
4,4,Bangalore,First Owner,Yamaha,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
7225,9362,Delhi,First Owner,Hero,48587.0,8.0,150.0
7226,9369,Bangalore,First Owner,Bajaj,60000.0,9.0,220.0
7227,9370,Jodhpur,First Owner,Harley-Davidson,3430.0,4.0,750.0
7228,9371,Hyderabad,First Owner,Bajaj,21300.0,4.0,400.0
7229,9372,Hyderabad,First Owner,Bajaj,7127.0,5.0,220.0

In [228]:
tvs_data=data[data['brand']=='TVS']

In [229]:
tvs_data

      Unnamed: 0       city        owner brand  kms_driven   age  power
0              0  Ahmedabad  First Owner   TVS     17654.0   3.0  110.0
3              3  Bangalore  First Owner   TVS     16329.0   4.0  180.0
48            52     Mumbai  First Owner   TVS     30000.0   5.0  160.0
109          114      Delhi  First Owner   TVS      8700.0   3.0  160.0
125          130    Barasat  First Owner   TVS     10500.0   5.0  125.0
...          ...        ...          ...   ...         ...   ...    ...
7173        9247  Ghaziabad  First Owner   TVS      4116.0   3.0  160.0
7196        9307     Alibag  First Owner   TVS     30000.0  10.0  160.0
7197        9312      Delhi  First Owner   TVS      9238.0   3.0  200.0
7205        9320     Hissar  First Owner   TVS     84916.0  14.0  150.0
7207        9322      Delhi  First Owner   TVS      4020.0   2.0  110.0

[477 rows x 7 columns]

In [201]:
tvs_First_owner_data = tvs_data[tvs_data['owner']=='First Owner']

In [202]:
tvs_First_owner_data

      Unnamed: 0       city        owner brand  kms_driven   age  power
0              0  Ahmedabad  First Owner   TVS     17654.0   3.0  110.0
3              3  Bangalore  First Owner   TVS     16329.0   4.0  180.0
48            52     Mumbai  First Owner   TVS     30000.0   5.0  160.0
109          114      Delhi  First Owner   TVS      8700.0   3.0  160.0
125          130    Barasat  First Owner   TVS     10500.0   5.0  125.0
...          ...        ...          ...   ...         ...   ...    ...
7173        9247  Ghaziabad  First Owner   TVS      4116.0   3.0  160.0
7196        9307     Alibag  First Owner   TVS     30000.0  10.0  160.0
7197        9312      Delhi  First Owner   TVS      9238.0   3.0  200.0
7205        9320     Hissar  First Owner   TVS     84916.0  14.0  150.0
7207        9322      Delhi  First Owner   TVS      4020.0   2.0  110.0

[442 rows x 7 columns]

In [203]:
tvs_First_owner_data

      Unnamed: 0       city        owner brand  kms_driven   age  power
0              0  Ahmedabad  First Owner   TVS     17654.0   3.0  110.0
3              3  Bangalore  First Owner   TVS     16329.0   4.0  180.0
48            52     Mumbai  First Owner   TVS     30000.0   5.0  160.0
109          114      Delhi  First Owner   TVS      8700.0   3.0  160.0
125          130    Barasat  First Owner   TVS     10500.0   5.0  125.0
...          ...        ...          ...   ...         ...   ...    ...
7173        9247  Ghaziabad  First Owner   TVS      4116.0   3.0  160.0
7196        9307     Alibag  First Owner   TVS     30000.0  10.0  160.0
7197        9312      Delhi  First Owner   TVS      9238.0   3.0  200.0
7205        9320     Hissar  First Owner   TVS     84916.0  14.0  150.0
7207        9322      Delhi  First Owner   TVS      4020.0   2.0  110.0

[442 rows x 7 columns]

In [204]:
tvs_First_owner_data[tvs_First_owner_data['kms_driven']<=50000]

      Unnamed: 0       city        owner brand  kms_driven   age  power
0              0  Ahmedabad  First Owner   TVS     17654.0   3.0  110.0
3              3  Bangalore  First Owner   TVS     16329.0   4.0  180.0
48            52     Mumbai  First Owner   TVS     30000.0   5.0  160.0
109          114      Delhi  First Owner   TVS      8700.0   3.0  160.0
125          130    Barasat  First Owner   TVS     10500.0   5.0  125.0
...          ...        ...          ...   ...         ...   ...    ...
7121        9158    Chennai  First Owner   TVS     13673.0   7.0  110.0
7173        9247  Ghaziabad  First Owner   TVS      4116.0   3.0  160.0
7196        9307     Alibag  First Owner   TVS     30000.0  10.0  160.0
7197        9312      Delhi  First Owner   TVS      9238.0   3.0  200.0
7207        9322      Delhi  First Owner   TVS      4020.0   2.0  110.0

[410 rows x 7 columns]

In [224]:
tvs_data=data[data['brand']=='Royal Enfield']
tvs_data

,Unnamed: 0,city,owner,brand,kms_driven,age,power
1,1,Delhi,First Owner,Royal Enfield,11000.0,4.0,350.0
8,8,Bangalore,First Owner,Royal Enfield,9190.0,3.0,350.0
9,9,Delhi,Second Owner,Royal Enfield,19000.0,7.0,500.0
20,23,Kalyan,First Owner,Royal Enfield,24520.0,5.0,500.0
32,36,Kochi,First Owner,Royal Enfield,39000.0,5.0,350.0
...,...,...,...,...,...,...,...
7187,9261,Guwahati,First Owner,Royal Enfield,8575.0,4.0,500.0
7204,9319,Chennai,First Owner,Royal Enfield,25000.0,10.0,350.0
7209,9337,Gurgaon,First Owner,Royal Enfield,8492.0,5.0,410.0
7210,9338,Delhi,First Owner,Royal Enfield,5000.0,5.0,410.0
7216,9344,Delhi,First Owner,Royal Enfield,56968.0,8.0,350.0

In [233]:
data

,Unnamed: 0,city,owner,brand,kms_driven,age,power
0,0,Ahmedabad,First Owner,TVS,17654.0,3.0,110.0
1,1,Delhi,First Owner,Royal Enfield,11000.0,4.0,350.0
2,2,Delhi,First Owner,Triumph,110.0,8.0,675.0
3,3,Bangalore,First Owner,TVS,16329.0,4.0,180.0
4,4,Bangalore,First Owner,Yamaha,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
7225,9362,Delhi,First Owner,Hero,48587.0,8.0,150.0
7226,9369,Bangalore,First Owner,Bajaj,60000.0,9.0,220.0
7227,9370,Jodhpur,First Owner,Harley-Davidson,3430.0,4.0,750.0
7228,9371,Hyderabad,First Owner,Bajaj,21300.0,4.0,400.0
7229,9372,Hyderabad,First Owner,Bajaj,7127.0,5.0,220.0

In [237]:
royal_data =data[(data['brand']=='Royal Enfield')&
                 (data['owner']==1.0)&
                 (data['kms_driven']<=50000)&
                 (data['age']<=2)]

#data.query("brand==Royal Enfield' and ")

In [238]:
royal_data

Empty DataFrame
Columns: [Unnamed: 0, city, owner, brand, kms_driven, age, power]
Index: []

In [240]:
data.query("brand=='Royal Enfield'")

,Unnamed: 0,city,owner,brand,kms_driven,age,power
1,1,Delhi,First Owner,Royal Enfield,11000.0,4.0,350.0
8,8,Bangalore,First Owner,Royal Enfield,9190.0,3.0,350.0
9,9,Delhi,Second Owner,Royal Enfield,19000.0,7.0,500.0
20,23,Kalyan,First Owner,Royal Enfield,24520.0,5.0,500.0
32,36,Kochi,First Owner,Royal Enfield,39000.0,5.0,350.0
...,...,...,...,...,...,...,...
7187,9261,Guwahati,First Owner,Royal Enfield,8575.0,4.0,500.0
7204,9319,Chennai,First Owner,Royal Enfield,25000.0,10.0,350.0
7209,9337,Gurgaon,First Owner,Royal Enfield,8492.0,5.0,410.0
7210,9338,Delhi,First Owner,Royal Enfield,5000.0,5.0,410.0
7216,9344,Delhi,First Owner,Royal Enfield,56968.0,8.0,350.0